services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.3.4
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
    working_dir: /app
    env_file:
      - .env
    networks:
      - ten_agent_network
  ten_agent_playground:
    image: ghcr.io/ten-framework/ten_agent_playground:0.7.0-45-g574e27a
    container_name: ten_agent_playground
    restart: always
    ports:
      - "3100:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:${SERVER_PORT}
      - TEN_DEV_SERVER_URL=http://ten_agent_dev:${GRAPH_DESIGNER_SERVER_PORT}
    depends_on:
      - ten_agent_dev

  ten_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.7.0-45-g574e27a
    container_name: ten_agent_demo
    restart: always
    ports:
      - "3102:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:${SERVER_PORT}
    depends_on:
      - ten_agent_dev

networks:
  ten_agent_network:
    driver: bridge
